development:
  sessions:
    default:
      database: try-csm-dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: try-csm-test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0